const Colors = {
  backgroundPrimary: "#FFFFFF",
  textPrimary: "#222222",
  textSecondary: "#555555",
  textMuted: "#888888",
  border: "#E0E0E0",
  CommonLoaderColor: "#9840cfff",
  ModalOverlayColor: "#00000050",
  PrimaryButtonBackgroundColor: "#FF6B95",
  ThemeBackgroundColor: "#e9ece8ff",
  PrimaryTextColor: "#212529",
  SecondaryTextColor: "#45455cff",
  DarkTextColor: "#0d2b43",
  TextErrorColor: "#e63131ff",
  TextBlueColor: "#1565C0",
  GreenBackgroundColor: "#e1fee8ff",
  InputBackgroundColor: "white",
  WhiteColor: "#ffffff",
  BlackColor: "#000000",
  GreyColor: "#D3D3D3",
  DarkGreyColor: "#9e9e9e",
  headerBAckground: "#fedbdbff",
  screenBackground: "#ffe9e9ff",
  // Dashboard Redesign Colors
  GradientOrangeStart: "#FF8C61",
  GradientOrangeEnd: "#FF6B95",
  GradientBlueStart: "#5E99FF",
  GradientBlueEnd: "#8C5EFF",
  TabActivePink: "#FFB6C1",
  TabInactiveText: "#888888",
  StatusGood: "#E1FEE8",
  StatusFair: "#FFF4D6",
  StatusBad: "#FFE9E9",
  StatusGoodText: "#2E7D32",
  StatusFairText: "#F57C00",
  StatusBadText: "#D32F2F",
  ButtonPink: "#FF4081",
  DashboardBackground: "#FFF5F5",
  // Full Dashboard Colors
  StressBlue: "#448AFF",
  StressCardBg: "#FFFFFF",
  DietCardBg: "#FFFFFF",
  DietIconBg: "#FFF8E1",
  ExpertCardBg: "#F3E5F5",
  ExpertButton: "#E040FB",
  ActivityIconBg: "#F5F5F5",
  ProgressBarBackground: "#E0E0E0",
  ProgressBarFill: "#448AFF",
  DietButton: "#FFB300",
  // Auth Colors
  AuthGradientStart: "#FF8C61",
  AuthGradientEnd: "#FF6B95",
  AuthBackgroundStart: "#FFF5F5",
  AuthBackgroundEnd: "#FFE9E9",
};
export default Colors;
